#build stage
FROM golang:alpine AS builder
RUN apk add --no-cache git
WORKDIR /go/src/app
COPY . .
RUN go get -d -v .
RUN go build -o /go/bin/app -v cmd/frontend/main.go

#final stage
FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /go/bin/app /app
COPY --from=builder /go/src/app/config /config
RUN ["chmod", "+x", "/app"]
ENTRYPOINT /app
LABEL Name=frontend Version=0.0.1
EXPOSE 8000
