apiVersion: v1
kind: ConfigMap
metadata:
  name: kvs-config
data:
  client_config.json: |
    {
        "ClientID": "client1",
        "FrontEndAddr": ":8000",
    }
  frontend_config.json: |
    {
        "ClientAPIListenAddr": ":8000",
        "StorageAPIListenAddr": ":8001",
    }
  storage_config.json: |
    {
      "StorageID": "storage1",
      "StorageAdd": ":8011",
      "FrontEndAddr": ":8001",
      "DiskPath": "/rpc-kvs/data"
    }
