apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-volume-claim
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  volumeName: storage-volume
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-volume
spec:
  claimRef:
    name: storage-volume-claim
    namespace: default
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ""
  hostPath:
    path: "/mnt/data"
