apiVersion: v1
kind: Service
metadata:
  name: storage-service
spec:
  selector:
    app: storage
  ports:
    - port: 80
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
        - name: storage
          image: "docker.io/kofeebrian/grpc-kvs-storage:v0.0.3"
          resources:
            limits:
              memory: "500Mi"
              cpu: "200m"
          ports:
            - containerPort: 8001
          volumeMounts:
            - mountPath: /rpc-kvs/data
              name: storage-data
            - mountPath: /config
              name: storage-config
      volumes:
        - name: storage-config
          configMap:
            name: storage-config
        - name: storage-data
          persistentVolumeClaim:
            claimName: storage-volume-claim
